#!/bin/sh
cp /media/boot/boot.ini /media/boot/boot.ini.old
cp /usr/share/bootini/boot.ini /media/boot/boot.ini
cp /media/boot/config.ini /media/boot/config.ini.old
cp /usr/share/bootini/config.ini /media/boot/config.ini


echo
echo
echo "A new boot.ini is installed."
echo "Any changes on your older bootini was replaced."
echo "Persistent custom settings from /media/boot/boot.ini.default have been restored"


dialog --msgbox "A new boot.ini is installed.
Any changes to boot.ini is lost, such as display configuration
Persistent custom settings from /media/boot/boot.ini.default have been restored
For reference your old boot.ini is saved to /media/boot/boot.ini.old" 0 0

